version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn --immutable && yarn dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_DB: todos
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: secret
      MYSQL_USER: root
  mysql:
    image: mysql:5.7
    volumes:
      - todo-db:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: secret

volumes:
  todo-db: